### PR TITLE
Feature/card logic PR before splitting the repo into two

### PR DESCRIPTION
**Pull request by connor-eg**

### CODE REVIEW

**Review by sean-bellinger — APPROVED** [review]
Looks fine.

**Review by reversedentistry — APPROVED** [review]
looks good

**Comment by connor-eg** [comment]
I make card class :D
put in production pl0x
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
amogus

**Review by Jahi-Citizen — APPROVED** [review]

**Review by TStutsman — COMMENTED** [review]
Looks good

**Review by sean-bellinger — COMMENTED** [review]
Looks good

**Review by TStutsman — APPROVED** [review]

**Review by reversedentistry — APPROVED** [review]

**Review by JonathanDemaree1 — APPROVED** [review]
A little sus but I'll let it slide

**Pull request merged**
